name: is2book_p39_env

channels:
  - conda-forge
dependencies:
  - python=3.9
  - cartopy=0.18.0 
  - netcdf4=1.5.6
  - matplotlib=3.4.3
  - pandas=1.3.3
  - numpy=1.20.3
  - scipy=1.6.3
  - pyproj=3.1.0
  - zarr=2.10.0
  - dask=2021.9.0
  - shapely=1.7.1
  - astropy=4.3.1
  - jupyterlab=3.1.12
  - ipykernel=6.17.1
  - jupyter_contrib_nbextensions=0.5.1
  - pip
  - datashader
  - firefox 
  - selenium
  - s3fs
  - jupyter-book
  - geoviews
  - holoviews
  - hvplot
  - boto3
  - xarray
  - fsspec
# giving problems  - geckodriver 
 # - pip: 
 #   - geoviews==1.9.1
 #   - jupyter-book==0.11.3 
 #   - gsutil
 #   - ghp-import